export const categories = {
  rows: {
    "Alcohol < 5%": (p) => p.alcoholPercentage < 5,
    "Alcohol 5–10%": (p) => p.alcoholPercentage >= 5 && p.alcoholPercentage <= 10,
    "Alcohol 10–13%": (p) => p.alcoholPercentage > 10 && p.alcoholPercentage <= 13,
    "Alcohol > 13%": (p) => p.alcoholPercentage > 13,
    "Price < 100 SEK": (p) => p.price < 100,
    "Price 100–200 SEK": (p) => p.price >= 100 && p.price <= 200,
    "Price 200–350 SEK": (p) => p.price > 200 && p.price <= 350,
    "Price > 350 SEK": (p) => p.price > 350,
    "Volume < 500 ml": (p) => p.volume < 500,
    "Volume = 750 ml": (p) => p.volume === 750,
    "Volume > 1000 ml": (p) => p.volume > 1000,
    "Bottle (glass)": (p) => p.packagingLevel1 === "Glasflaska",
    "Can": (p) => p.packagingLevel1 === "Burk",
    "Box": (p) => p.packagingLevel1 === "Box",
  },
  columns: {
    "Sweden": (p) => p.country === "Sverige",
    "France": (p) => p.country === "Frankrike",
    "Italy": (p) => p.country === "Italien",
    "Spain": (p) => p.country === "Spanien",
    "Germany": (p) => p.country === "Tyskland",
    "USA": (p) => p.country === "USA",
    "Argentina": (p) => p.country === "Argentina",
    "Chile": (p) => p.country === "Chile",
    "Australia": (p) => p.country === "Australien",
    "Alsace": (p) => p.originLevel1 === "Alsace",
    "Bordeaux": (p) => p.originLevel1 === "Bordeaux",
    "Tuscany": (p) => p.originLevel1 === "Toscana",
    "Rioja": (p) => p.originLevel1 === "Rioja",
    "Beer": (p) => p.categoryLevel1 === "Öl",
    "IPA": (p) => p.categoryLevel2 === "IPA",
    "Lager": (p) => p.categoryLevel2 === "Lager",
    "Stout": (p) => p.categoryLevel2 === "Stout",
    "Wheat Ale": (p) => p.categoryLevel2 === "Veteöl",
    "Pale Ale": (p) => p.categoryLevel2 === "Pale Ale",
    "Sour Beer": (p) => p.categoryLevel2 === "Suröl",
    "Porter": (p) => p.categoryLevel2 === "Porter",
    "Wine": (p) => p.categoryLevel1 === "Vin",
    "Spirits": (p) => p.categoryLevel1 === "Sprit",
    "White wine": (p) => p.categoryLevel2 === "Vitt vin",
    "Red wine": (p) => p.categoryLevel2 === "Rött vin",
    "Sparkling wine": (p) => p.categoryLevel2 === "Mousserande vin",
    "Organic": (p) => p.isOrganic,
    "Kosher": (p) => p.isKosher,
  }
};